org: ecastrov
app: travel-assistant
service: travel-api
frameworkVersion: "4"

build:
  esbuild:
    bundle: true

provider:
  name: aws
  runtime: nodejs22.x
  environment:
    TABLE_NAME: !Ref TravelsTable
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Scan
          Resource: !GetAtt TravelsTable.Arn

functions:
  createTravel:
    handler: src/create.handler
    events:
      - httpApi:
          path: /travels
          method: post

  getTravel:
    handler: src/read.handler
    events:
      - httpApi:
          path: /travels
          method: get

  updateTravel:
    handler: src/update.handler
    events:
      - httpApi:
          path: /travels/{id}
          method: put

  deleteTravel:
    handler: src/delete.handler
    events:
      - httpApi:
          path: /travels/{id}
          method: delete

plugins:
  - serverless-offline

resources:
  Resources:
    TravelsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: travels
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
